services:
  app:
    ports:
      - "8086:80"
    build: Dockerfile
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=bookstore
      - MYSQL_ROOT_PASSWORD=rootpwd
    volumes:
      - db-data:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db

volumes:
  db-data: