name: Main CI workflow
on:
  push:
jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: execute phpstan
        uses: php-actions/phpstan@v3
        with:
          level: 1
          path: src/
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build project
        run: echo "build"